language: python
sudo: false
cache: pip
dist: bionic


matrix:
  fast_finish: true
  allow_failures:
  - python: "3.4"
    python: "3.5"

install:
  - "python -m pip install ${PIP} setuptools wheel"
  - "python -m pip install pytest pytest-xdist pytest-cov pytest-timeout"
  - "python -m pip install -e .[tests]"
script:
  - "python -m pytest -v -n 8 tests/"

jobs:
  include:
		- &test-pip20
      stage: test-pip20
      python: "3.6"
      env: PIP="pip==20.0.2"
    - <<: *test-pip20
      python: "3.8"
     - <<: *test-pip20
      python: "3.7"
    - <<: *test-pip20
      python: "3.5"
      dist: xenial
      sudo: required
    - <<: *test-pip20
      python: "3.4"
      dist: xenial
      sudo: required
    - <<: *test-pip20
      python: "2.7"
    - &test-pip193
      stage: test-pip193
      python: "3.6"
      env: PIP="pip==19.3.1"
    - <<: *test-pip193
      python: "3.8"
     - <<: *test-pip193
      python: "3.7"
    - <<: *test-pip193
      python: "3.5"
      dist: xenial
      sudo: required
    - <<: *test-pip193
      python: "3.4"
      dist: xenial
      sudo: required
    - <<: *test-pip193
      python: "2.7"
		- &test-pip19
      stage: test-pip19
      python: "3.6"
      env: PIP="pip==19.0.3"
    - <<: *test-pip19
      python: "3.8"
     - <<: *test-pip19
      python: "3.7"
    - <<: *test-pip19
      python: "3.5"
      dist: xenial
      sudo: required
    - <<: *test-pip19
      python: "3.4"
      dist: xenial
      sudo: required
    - <<: *test-pip19
      python: "2.7"
    - &test-pip181
      stage: test-pip181
      python: "3.6"
      env: PIP="pip==18.1"
    - <<: *test-pip181
      python: "3.7"
    - <<: *test-pip181
      python: "3.5"
      dist: xenial
      sudo: required
    - <<: *test-pip181
      python: "3.4"
      dist: xenial
      sudo: required
    - <<: *test-pip181
      python: "2.7"
    - &test-pipmaster
      stage: test-pipmaster
      python: "3.6"
      env: PIP="-e git+https://github.com/pypa/pip@master#egg=pip"
      install:
        - "python -m pip install ${PIP}"
        - "python -m pip install pytest pytest-xdist pytest-cov pytest-timeout"
        - "python -m pip install -e .[tests] --no-use-pep517"
    - <<: *test-pipmaster
      python: "3.7"
    - <<: *test-pipmaster
      python: "3.5"
      dist: xenial
      sudo: required
    - <<: *test-pipmaster
      python: "3.4"
      dist: xenial
      sudo: required
    - <<: *test-pipmaster
      python: "2.7"
    - &test-pip9
      stage: test-pip9
      python: "3.6"
      env: PIP="pip==9.0.3"
    - <<: *test-pip9
      python: "3.7"
    - <<: *test-pip9
      python: "3.5"
      dist: xenial
      sudo: required
    - <<: *test-pip9
      python: "3.4"
      dist: xenial
      sudo: required
    - <<: *test-pip9
      python: "2.7"
    - &test-pip10
      stage: test-pip10
      python: "3.6"
      env: PIP="pip==10.0.1"
    - <<: *test-pip10
      python: "3.7"
    - <<: *test-pip10
      python: "3.5"
      dist: xenial
      sudo: required
    - <<: *test-pip10
      python: "3.4"
      dist: xenial
      sudo: required
    - <<: *test-pip10
      python: "2.7"
    - &test-pip180
      stage: test-pip180
      python: "3.6"
      env: PIP="pip==18.0"
    - <<: *test-pip180
      python: "3.7"
    - <<: *test-pip180
      python: "3.5"
      dist: xenial
      sudo: required
    - <<: *test-pip180
      python: "3.4"
      dist: xenial
      sudo: required
    - <<: *test-pip180
      python: "2.7"
    - stage: packaging
      python: "3.6"
      if: env(PIP) == "pip==19.0.3" && python == "3.6"
      install:
        - "python -m pip install --upgrade twine readme-renderer[md]"
      script:
        - "python setup.py sdist bdist_wheel"
        - "twine check dist/*"
    - stage: coverage
      python: "3.6"
      if: env(PIP) == "pip==19.0.3" && python == "3.6"
      install:
        - "pip install --upgrade pip pytest-timeout"
        - "pip install --upgrade -e .[tests]"
      script:
        - "pytest -n auto --timeout 300 --cov=pip_shims --cov-report=term-missing --cov-report=xml --cov-report=html tests"
