language: python
sudo: false
cache: pip
dist: trusty


matrix:
  fast_finish: true
  allow_failures:
  - python: "3.4"

install:
  - "python -m pip install ${PIP}"
  - "python -m pip install pytest pytest-xdist pytest-cov pytest-timeout"
  - "python -m pip install -e .[tests]"
script:
  - "python -m pytest -v -n 8 tests/"

jobs:
  include:
    - &test-pip9
      stage: test-pip9
      python: "3.6"
      env: PIP="pip==9.0.3"
    - <<: *test-pip9
      python: "3.7"
      dist: xenial
      sudo: required
    - <<: *test-pip9
      python: "3.5"
    - <<: *test-pip9
      python: "3.4"
    - <<: *test-pip9
      python: "2.7"
    - &test-pip10
      stage: test-pip10
      python: "3.6"
      env: PIP="pip==10.0.1"
    - <<: *test-pip10
      python: "3.7"
      dist: xenial
      sudo: required
    - <<: *test-pip10
      python: "3.5"
    - <<: *test-pip10
      python: "3.4"
    - <<: *test-pip10
      python: "2.7"
    - &test-pip180
      stage: test-pip180
      python: "3.6"
      env: PIP="pip==18.0"
    - <<: *test-pip180
      python: "3.7"
      dist: xenial
      sudo: required
    - <<: *test-pip180
      python: "3.5"
    - <<: *test-pip180
      python: "3.4"
    - <<: *test-pip180
      python: "2.7"
    - &test-pip181
      stage: test-pip181
      python: "3.6"
      env: PIP="pip==18.1"
    - <<: *test-pip181
      python: "3.7"
      dist: xenial
      sudo: required
    - <<: *test-pip181
      python: "3.5"
    - <<: *test-pip181
      python: "3.4"
    - <<: *test-pip181
      python: "2.7"
    - &test-pipmaster
      stage: test-pipmaster
      python: "3.6"
      env: PIP="-e git+https://github.com/pypa/pip@master#egg=pip"
    - <<: *test-pipmaster
      python: "3.7"
      dist: xenial
      sudo: required
    - <<: *test-pipmaster
      python: "3.5"
    - <<: *test-pipmaster
      python: "3.4"
    - <<: *test-pipmaster
      python: "2.7"
    - stage: packaging
      python: "3.6"
      if: env(PIP) == "pip==18.1" && python == "3.6"
      install:
        - "python -m pip install --upgrade check-manifest readme-renderer"
      script:
        - "python setup.py check -m -r -s"
    - stage: coverage
      python: "3.6"
      if: env(PIP) == "pip==18.1" && python == "3.6"
      install:
        - "pip install --upgrade pip pytest-timeout"
        - "pip install --upgrade -e .[tests]"
      script:
        - "pytest -n auto --timeout 300 --cov=pip_shims --cov-report=term-missing --cov-report=xml --cov-report=html tests"
