language: python
sudo: false
cache: pip
dist: trusty

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - PIP=9.0.3
  - PIP=10.0.1
  - PIP=18.0
  - PIP=18.1
  - PIP="-e git+https://github.com/pypa/pip@master#egg=pip"

matrix:
  fast_finish: true
  allow_failures:
  - python: "3.4"

install:
  - "python -m pip install pip==${PIP} pytest pytest-xdist pytest-cov pytest-timeout"
  - "python -m pip install -e .[tests]"
script:
  - "python -m pytest -v -n 8 tests/"

jobs:
  include:
    - stage: test
    - python: "3.4"
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "3.6"
    - python: "2.7"
    - python: "3.5"
    - stage: packaging
      python: "3.6"
      if: env(PIP) == 18.1 && python == "3.6"
      install:
        - "python -m pip install --upgrade check-manifest readme-renderer"
      script:
        - "python setup.py check -m -r -s"
    - stage: coverage
      python: "3.6"
      if: env(PIP) == 18.1 && python == "3.6"
      install:
        - "pip install --upgrade pip pytest-timeout"
        - "pip install --upgrade -e .[tests]"
      script:
        - "pytest -n auto --timeout 300 --cov=pip_shims --cov-report=term-missing --cov-report=xml --cov-report=html tests"
