environment:
  matrix:
    # Unit and integration tests.
    - PYTHON: "C:\\Python27"
      RUN_INTEGRATION_TESTS: "True"
    - PYTHON: "C:\\Python36-x64"
      RUN_INTEGRATION_TESTS: "True"
    # Unit tests only.
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python27-x64"
      PIP: "18.1"
    - PYTHON: "C:\\Python34-x64"
      PIP: "18.1"
    - PYTHON: "C:\\Python35-x64"
      PIP: "18.1"
    - PYTHON: "C:\\Python36-x64"
      PIP: "18.1"
    - PYTHON: "C:\\Python27-x64"
      PIP: "18.0"
    - PYTHON: "C:\\Python34-x64"
      PIP: "18.0"
    - PYTHON: "C:\\Python35-x64"
      PIP: "18.0"
    - PYTHON: "C:\\Python36-x64"
      PIP: "18.0"
    - PYTHON: "C:\\Python27-x64"
      PIP: "10.0.1"
    - PYTHON: "C:\\Python34-x64"
      PIP: "10.0.1"
    - PYTHON: "C:\\Python35-x64"
      PIP: "10.0.1"
    - PYTHON: "C:\\Python36-x64"
      PIP: "10.0.1"
    - PYTHON: "C:\\Python27-x64"
      PIP: "9.0.3"
    - PYTHON: "C:\\Python34-x64"
      PIP: "9.0.3"
    - PYTHON: "C:\\Python35-x64"
      PIP: "9.0.3"
    - PYTHON: "C:\\Python36-x64"
      PIP: "9.0.3"

install:
  - ps: |

      $py_path = resolve-path $env:PYTHON

      $py_path = $py_path -replace ' ', '` '

      $scripts_path = join-path -path $py_path -childpath "Scripts"

      $env:PATH="$py_path.ToString();$scripts_path.ToString();$env:PATH"

      $py_exe = join-path -path $py_path -childpath python.exe

      if ( $env:PIP ) { $pip = "pip==$env:PIP" } else { $pip = "pip" }

      Invoke-Expression "$py_exe --version"
      If ($LastExitCode -ne 0) {
        exit $LastExitCode
      }

      Invoke-Expression "$py_exe -m pip install --upgrade $pip"
      If ($LastExitCode -ne 0) {
        exit $LastExitCode
      }

      Invoke-Expression "$py_exe -m pip install -e .[tests]"
      If ($LastExitCode -ne 0) {
        exit $LastExitCode
      }


build: off

test_script:
  # Shorten paths, workaround https://bugs.python.org/issue18199
  - "subst T: %TEMP%"
  - "set TEMP=T:\\"
  - "set TMP=T:\\"
  - python -m pytest -n auto --junitxml=%cd%\junit-results.xml tests

on_finish:
  # We can get a nice display of test results in the "test" tab with py.test
  # For now, this does nothing.
  - ps: |
      If (Test-Path .\junit-results.xml) {
        (new-object net.webclient).UploadFile(
          "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)",
          (Resolve-Path .\junit-results.xml)
        )
      }
      $LastExitCode = 0
