# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- template: .azure-pipelines/templates/run-tests.yml
  parameters:
    vmImage: 'Ubuntu-latest'
    jobName: TestLinux
    pythonVersions: ["3.7", "3.6", "3.5", "2.7"]
    pipVersions: ["pip==9.0.3", "pip==10.0.1", "pip==18.0", "pip==19.0.3", "pip==19.1.1", "pip==19.2.3", "pip==19.3.1", "git+https://github.com/pypa/pip@master#egg=pip"]

- template: .azure-pipelines/templates/run-tests.yml
  parameters:
    vmImage: 'windows-2019'
    jobName: TestWindows
    pythonVersions: ["3.7", "3.6", "3.5", "2.7"]
    pipVersions: ["pip==9.0.3", "pip==10.0.1", "pip==18.0", "pip==19.0.3", "pip==19.1.1", "pip==19.2.3", "pip==19.3.1", "git+https://github.com/pypa/pip@master#egg=pip"]

- template: .azure-pipelines/templates/run-tests.yml
  parameters:
    vmImage: 'macOS-10.13'
    jobName: TestMacOS
    pythonVersions: ["3.7", "3.6", "3.5", "2.7"]
    pipVersions: ["pip==9.0.3", "pip==10.0.1", "pip==18.0", "pip==19.0.3", "pip==19.1.1", "pip==19.2.3", "pip==19.3.1", "git+https://github.com/pypa/pip@master#egg=pip"]

- job: BuildPackage
  dependsOn:
    - TestLinux
    - TestWindows
    - TestMacOS
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: .azure-pipelines/templates/build-package.yml
