# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- template: .azure-pipelines/templates/run-tests.yml
  parameters:
    vmImage: 'Ubuntu-16.04'
    jobName: TestLinux

- template: .azure-pipelines/templates/run-tests.yml
  parameters:
    vmImage: 'windows-2019'
    jobName: TestWindows

- template: .azure-pipelines/templates/run-tests.yml
  parameters:
    vmImage: 'macOS-10.13'
    jobName: TestMacOS

- job: BuildPackage
  dependsOn:
    - TestLinux
    - TestWindows
    - TestMacOS
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: .azure-pipelines/templates/build-package.yml
