steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
    displayName: Use Python 3.7

  - template: install-dependencies.yml

  - script: |
      pip install invoke towncrier readme-renderer[md] twine parver
      inv clean
      inv build
      twine check dist/*
    displayName: Build Package
  - task: CopyFiles@2
    inputs:
      sourceFolder: dist/
      contents: "**"
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: Copy Artifacts

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: PackageArtifacts
    displayName: Publish Artifacts
