parameters:
  pythonVersions: []
  pipVersions: []
  vmImage: ''
  jobName: ''

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      ${{ each py in parameters.pythonVersions }}:
        ${{ each pip in parameters.pipVersions }}:
          ${{ if contains(pip, 'github.com') }}:
            ${{ format('{0}-PIPMaster', py) }}:
              python.version: ${{ py }}
              PIP_VERSION: ${{ pip }}
          ${{ if not(contains(pip, 'github.com')) }}:
            ${{ format('{0}{1}', py, pip) }}:
              python.version: ${{ py }}
              PIP_VERSION: ${{ pip }}
  variables:
  - group: CI
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(python.version)
    displayName: Use Python $(python.version)

  - script: |
      python -m pip install pipenv
      python -m pipenv run pip install $(PIP_VERSION) --upgrade
      pipenv install --dev
    displayName: 'Install Dependencies'
    env:
      PYTHONWARNINGS: ignore:DEPRECATION
  - script: pipenv run pytest -ra --junitxml=junit/test-results.xml tests/
    displayName: 'Run PyTest'
    env:
      PYTHONWARNINGS: ignore:DEPRECATION
#   - ${{ if eq(parameters.vmImage, 'windows-2019') }}:
#     - powershell: |
#         python -m pip install virtualenv --upgrade
#         python -m virtualenv .venv
#         . .venv/Scripts/activate.ps1
#         ./.venv/Scripts/pip install $(PIP_VERSION) setuptools wheel pytest-xdist pytest-cov pytest-timeout -e .[tests] --upgrade
#       displayName: Install Dependencies
#       env:
#         PYTHONWARNINGS: ignore:DEPRECATION
#     - powershell: |
#         . .venv/Scripts/activate.ps1
#         pytest -ra --junitxml=junit/test-results.xml tests/
#       displayName: 'Run Pytest'
#       env:
#         PYTHONWARNINGS: ignore:DEPRECATION

#   - ${{ if ne(parameters.vmImage, 'windows-2019') }}:
#     - script: |
#         python -m pip install virtualenv --upgrade
#         python -m virtualenv .venv
#         . ./.venv/bin/activate && \
#             PATH="$(pwd)/.venv/bin:${PATH}" ./.venv/bin/python -m pip install $(PIP_VERSION) setuptools wheel pytest-xdist pytest-cov pytest-timeout -e .[tests] --upgrade
#       displayName: Install Dependencies
#       env:
#         PYTHONWARNINGS: ignore:DEPRECATION
#     - script: |
#         . ./.venv/bin/activate && \
#             PATH="$(pwd)/.venv/bin:${PATH}" ./.venv/bin/python -m pytest -ra --junitxml=junit/test-results.xml tests/
#       displayName: 'Run Pytest'
#       env:
#         PYTHONWARNINGS: ignore:DEPRECATION

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: '$(Agent.OS) - $(Build.DefinitionName) - Python $(python.version)'
    condition: succeededOrFailed()
    displayName: 'Publish Test Results'
