name: Create Release & Upload To Test PyPI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+.*

jobs:
  build:
    name: pip-shims PyPI Upload
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install latest tools for build
      run: |
        python -m pip install --upgrade pip setuptools wheel pipenv invoke
        python -m pipenv install --dev --pre
        python -m pipenv run pip install invoke
    - name: Build wheels
      run: |
        python -m pipenv run inv build
    - name: Upload to PyPI via Twine
      run: |
        twine upload --verbose -u '__token__' -p '${{ secrets.TEST_PYPI_TOKEN }}' --repository-url https://test.pypi.org/legacy/ dist/*
